### ISSUE TITLE
ESearch Against PubMed Database

### ISSUE THREAD

**Issue by freshottr** [CS599-MEDLINE/pubminer-ui-investigation#18]
Currently we are searching against the PubMed Central database, but PMC doesn't support all of PubMed's query features (e.g. by `Publication Type`). The clients will likely want to use PubMed queries, even though we will ultimately only the subset of articles in PMC. We can probably accomplish this by running submitted queries against PubMed, then use the `ELink` API to get PMC IDs from associated with the search results.

The flow will probably be `eSearch => eLink => eSummary`, but that needs some additional research

**Comment by freshottr** [comment]
we should also enrich the query that we send to PubMed to try to limit the results to valid clinical trials.  You can look for the exact filter criteria @ddowey references in the slack `#general` channel

**Comment by joeb37** [comment]
https://docs.google.com/document/d/1FIOP12wXvJDeLaIpFgnexU9gIxHrIPTB0r8cv7VLpSU/edit

**Comment by freshottr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use terms to enrich E-Search](https://trello.com/c/dSon5fUB/2-use-terms-to-enrich-e-search)

**Comment by freshottr** [comment]
Resolved
