### ISSUE TITLE
Clean Up Summary Results Data

### ISSUE THREAD

**Issue by freshottr** [CS599-MEDLINE/pubminer-ui-investigation#54]
We are currently sending a lot more data back to the UI than is being used for summary results. One example is the `articleids` section that is included for every item. I suspect much of this data isn't needed, it was just expedient to return everything when we started developing. We should look at developing more formal/structured responses from our APIs and removing data that isn't needed.

**Comment by joeb37** [comment]
This is the data used to build the UI.  Assume anything else is unnecessary.
+ item.uid
+ item.title
+ item.pmid
+ item.pmcid
+ item.authors
+ item.pubdate
+ item.sentences
+ item.table1
+ abstract

**Comment by freshottr** [comment]
Thanks for the detailed list @joeb37!
